// Country-specific configurations for all 197 countries
export const countryConfigs: Record<string, { hl: string; googleDomain: string }> = {
    'af': { hl: 'ps', googleDomain: 'google.com' }, // Afghanistan (Pashto)
    'al': { hl: 'sq', googleDomain: 'google.al' }, // Albania (Albanian)
    'dz': { hl: 'ar', googleDomain: 'google.dz' }, // Algeria (Arabic)
    'ad': { hl: 'ca', googleDomain: 'google.ad' }, // Andorra (Catalan)
    'ao': { hl: 'pt', googleDomain: 'google.co.ao' }, // Angola (Portuguese)
    'ag': { hl: 'en', googleDomain: 'google.com.ag' }, // Antigua and Barbuda (English)
    'ar': { hl: 'es', googleDomain: 'google.com.ar' }, // Argentina (Spanish)
    'am': { hl: 'hy', googleDomain: 'google.am' }, // Armenia (Armenian)
    'au': { hl: 'en', googleDomain: 'google.com.au' }, // Australia (English)
    'at': { hl: 'de', googleDomain: 'google.at' }, // Austria (German)
    'az': { hl: 'az', googleDomain: 'google.az' }, // Azerbaijan (Azerbaijani)
    'bs': { hl: 'en', googleDomain: 'google.bs' }, // Bahamas (English)
    'bh': { hl: 'ar', googleDomain: 'google.com.bh' }, // Bahrain (Arabic)
    'bd': { hl: 'bn', googleDomain: 'google.com.bd' }, // Bangladesh (Bengali)
    'bb': { hl: 'en', googleDomain: 'google.com.bb' }, // Barbados (English)
    'by': { hl: 'be', googleDomain: 'google.by' }, // Belarus (Belarusian)
    'be': { hl: 'nl', googleDomain: 'google.be' }, // Belgium (Dutch primary, also French)
    'bz': { hl: 'en', googleDomain: 'google.com.bz' }, // Belize (English)
    'bj': { hl: 'fr', googleDomain: 'google.bj' }, // Benin (French)
    'bt': { hl: 'dz', googleDomain: 'google.bt' }, // Bhutan (Dzongkha)
    'bo': { hl: 'es', googleDomain: 'google.com.bo' }, // Bolivia (Spanish)
    'ba': { hl: 'bs', googleDomain: 'google.ba' }, // Bosnia and Herzegovina (Bosnian)
    'bw': { hl: 'en', googleDomain: 'google.co.bw' }, // Botswana (English)
    'br': { hl: 'pt', googleDomain: 'google.com.br' }, // Brazil (Portuguese)
    'bn': { hl: 'ms', googleDomain: 'google.com.bn' }, // Brunei (Malay)
    'bg': { hl: 'bg', googleDomain: 'google.bg' }, // Bulgaria (Bulgarian)
    'bf': { hl: 'fr', googleDomain: 'google.bf' }, // Burkina Faso (French)
    'bi': { hl: 'fr', googleDomain: 'google.bi' }, // Burundi (French)
    'kh': { hl: 'km', googleDomain: 'google.com.kh' }, // Cambodia (Khmer)
    'cm': { hl: 'fr', googleDomain: 'google.cm' }, // Cameroon (French primary, also English)
    'ca': { hl: 'en', googleDomain: 'google.ca' }, // Canada (English primary, also French)
    'cv': { hl: 'pt', googleDomain: 'google.cv' }, // Cape Verde (Portuguese)
    'cf': { hl: 'fr', googleDomain: 'google.cf' }, // Central African Republic (French)
    'td': { hl: 'fr', googleDomain: 'google.td' }, // Chad (French)
    'cl': { hl: 'es', googleDomain: 'google.cl' }, // Chile (Spanish)
    'cn': { hl: 'zh', googleDomain: 'google.cn' }, // China (Chinese)
    'co': { hl: 'es', googleDomain: 'google.com.co' }, // Colombia (Spanish)
    'km': { hl: 'ar', googleDomain: 'google.km' }, // Comoros (Arabic primary, also French)
    'cd': { hl: 'fr', googleDomain: 'google.cd' }, // Congo, Democratic Republic (French)
    'cg': { hl: 'fr', googleDomain: 'google.cg' }, // Congo, Republic (French)
    'cr': { hl: 'es', googleDomain: 'google.co.cr' }, // Costa Rica (Spanish)
    'hr': { hl: 'hr', googleDomain: 'google.hr' }, // Croatia (Croatian)
    'cu': { hl: 'es', googleDomain: 'google.com.cu' }, // Cuba (Spanish)
    'cy': { hl: 'el', googleDomain: 'google.com.cy' }, // Cyprus (Greek primary, also Turkish)
    'cz': { hl: 'cs', googleDomain: 'google.cz' }, // Czech Republic (Czech)
    'dk': { hl: 'da', googleDomain: 'google.dk' }, // Denmark (Danish)
    'dj': { hl: 'fr', googleDomain: 'google.dj' }, // Djibouti (French primary, also Arabic)
    'dm': { hl: 'en', googleDomain: 'google.dm' }, // Dominica (English)
    'do': { hl: 'es', googleDomain: 'google.com.do' }, // Dominican Republic (Spanish)
    'tl': { hl: 'pt', googleDomain: 'google.tl' }, // East Timor (Portuguese)
    'ec': { hl: 'es', googleDomain: 'google.com.ec' }, // Ecuador (Spanish)
    'eg': { hl: 'ar', googleDomain: 'google.com.eg' }, // Egypt (Arabic)
    'sv': { hl: 'es', googleDomain: 'google.com.sv' }, // El Salvador (Spanish)
    'gq': { hl: 'es', googleDomain: 'google.gq' }, // Equatorial Guinea (Spanish)
    'er': { hl: 'ti', googleDomain: 'google.com' }, // Eritrea (Tigrinya primary)
    'ee': { hl: 'et', googleDomain: 'google.ee' }, // Estonia (Estonian)
    'sz': { hl: 'en', googleDomain: 'google.co.sz' }, // Eswatini (English primary)
    'et': { hl: 'am', googleDomain: 'google.com.et' }, // Ethiopia (Amharic)
    'fj': { hl: 'en', googleDomain: 'google.com.fj' }, // Fiji (English)
    'fi': { hl: 'fi', googleDomain: 'google.fi' }, // Finland (Finnish)
    'fr': { hl: 'fr', googleDomain: 'google.fr' }, // France (French)
    'ga': { hl: 'fr', googleDomain: 'google.ga' }, // Gabon (French)
    'gm': { hl: 'en', googleDomain: 'google.gm' }, // Gambia (English)
    'ge': { hl: 'ka', googleDomain: 'google.ge' }, // Georgia (Georgian)
    'de': { hl: 'de', googleDomain: 'google.de' }, // Germany (German)
    'gh': { hl: 'en', googleDomain: 'google.com.gh' }, // Ghana (English)
    'gr': { hl: 'el', googleDomain: 'google.gr' }, // Greece (Greek)
    'gd': { hl: 'en', googleDomain: 'google.gd' }, // Grenada (English)
    'gt': { hl: 'es', googleDomain: 'google.com.gt' }, // Guatemala (Spanish)
    'gn': { hl: 'fr', googleDomain: 'google.gn' }, // Guinea (French)
    'gw': { hl: 'pt', googleDomain: 'google.gw' }, // Guinea-Bissau (Portuguese)
    'gy': { hl: 'en', googleDomain: 'google.gy' }, // Guyana (English)
    'ht': { hl: 'fr', googleDomain: 'google.ht' }, // Haiti (French primary, also Haitian Creole)
    'hn': { hl: 'es', googleDomain: 'google.hn' }, // Honduras (Spanish)
    'hu': { hl: 'hu', googleDomain: 'google.hu' }, // Hungary (Hungarian)
    'is': { hl: 'is', googleDomain: 'google.is' }, // Iceland (Icelandic)
    'in': { hl: 'hi', googleDomain: 'google.co.in' }, // India (Hindi primary, also English)
    'id': { hl: 'id', googleDomain: 'google.co.id' }, // Indonesia (Indonesian)
    'ir': { hl: 'fa', googleDomain: 'google.ir' }, // Iran (Persian)
    'iq': { hl: 'ar', googleDomain: 'google.iq' }, // Iraq (Arabic)
    'ie': { hl: 'en', googleDomain: 'google.ie' }, // Ireland (English)
    'il': { hl: 'he', googleDomain: 'google.co.il' }, // Israel (Hebrew)
    'it': { hl: 'it', googleDomain: 'google.it' }, // Italy (Italian)
    'ci': { hl: 'fr', googleDomain: 'google.ci' }, // Ivory Coast (French)
    'jm': { hl: 'en', googleDomain: 'google.com.jm' }, // Jamaica (English)
    'jp': { hl: 'ja', googleDomain: 'google.co.jp' }, // Japan (Japanese)
    'jo': { hl: 'ar', googleDomain: 'google.jo' }, // Jordan (Arabic)
    'kz': { hl: 'kk', googleDomain: 'google.kz' }, // Kazakhstan (Kazakh)
    'ke': { hl: 'sw', googleDomain: 'google.co.ke' }, // Kenya (Swahili primary, also English)
    'ki': { hl: 'en', googleDomain: 'google.ki' }, // Kiribati (English)
    'xk': { hl: 'sq', googleDomain: 'google.com' }, // Kosovo (Albanian, no specific domain)
    'kw': { hl: 'ar', googleDomain: 'google.com.kw' }, // Kuwait (Arabic)
    'kg': { hl: 'ky', googleDomain: 'google.kg' }, // Kyrgyzstan (Kyrgyz)
    'la': { hl: 'lo', googleDomain: 'google.la' }, // Laos (Lao)
    'lv': { hl: 'lv', googleDomain: 'google.lv' }, // Latvia (Latvian)
    'lb': { hl: 'ar', googleDomain: 'google.com.lb' }, // Lebanon (Arabic)
    'ls': { hl: 'en', googleDomain: 'google.co.ls' }, // Lesotho (English)
    'lr': { hl: 'en', googleDomain: 'google.lr' }, // Liberia (English)
    'ly': { hl: 'ar', googleDomain: 'google.com.ly' }, // Libya (Arabic)
    'li': { hl: 'de', googleDomain: 'google.li' }, // Liechtenstein (German)
    'lt': { hl: 'lt', googleDomain: 'google.lt' }, // Lithuania (Lithuanian)
    'lu': { hl: 'fr', googleDomain: 'google.lu' }, // Luxembourg (French primary)
    'mg': { hl: 'mg', googleDomain: 'google.mg' }, // Madagascar (Malagasy)
    'mw': { hl: 'en', googleDomain: 'google.mw' }, // Malawi (English)
    'my': { hl: 'ms', googleDomain: 'google.com.my' }, // Malaysia (Malay)
    'mv': { hl: 'dv', googleDomain: 'google.mv' }, // Maldives (Dhivehi)
    'ml': { hl: 'fr', googleDomain: 'google.ml' }, // Mali (French)
    'mt': { hl: 'mt', googleDomain: 'google.com.mt' }, // Malta (Maltese)
    'mh': { hl: 'en', googleDomain: 'google.com' }, // Marshall Islands (English)
    'mr': { hl: 'ar', googleDomain: 'google.mr' }, // Mauritania (Arabic)
    'mu': { hl: 'en', googleDomain: 'google.mu' }, // Mauritius (English)
    'mx': { hl: 'es', googleDomain: 'google.com.mx' }, // Mexico (Spanish)
    'fm': { hl: 'en', googleDomain: 'google.fm' }, // Micronesia (English)
    'md': { hl: 'ro', googleDomain: 'google.md' }, // Moldova (Romanian)
    'mc': { hl: 'fr', googleDomain: 'google.mc' }, // Monaco (French)
    'mn': { hl: 'mn', googleDomain: 'google.mn' }, // Mongolia (Mongolian)
    'me': { hl: 'sr', googleDomain: 'google.me' }, // Montenegro (Serbian)
    'ma': { hl: 'ar', googleDomain: 'google.co.ma' }, // Morocco (Arabic)
    'mz': { hl: 'pt', googleDomain: 'google.co.mz' }, // Mozambique (Portuguese)
    'mm': { hl: 'my', googleDomain: 'google.com.mm' }, // Myanmar (Burmese)
    'na': { hl: 'en', googleDomain: 'google.com.na' }, // Namibia (English)
    'nr': { hl: 'en', googleDomain: 'google.nr' }, // Nauru (English)
    'np': { hl: 'ne', googleDomain: 'google.com.np' }, // Nepal (Nepali)
    'nl': { hl: 'nl', googleDomain: 'google.nl' }, // Netherlands (Dutch)
    'nz': { hl: 'en', googleDomain: 'google.co.nz' }, // New Zealand (English)
    'ni': { hl: 'es', googleDomain: 'google.com.ni' }, // Nicaragua (Spanish)
    'ne': { hl: 'fr', googleDomain: 'google.ne' }, // Niger (French)
    'ng': { hl: 'en', googleDomain: 'google.com.ng' }, // Nigeria (English)
    'kp': { hl: 'ko', googleDomain: 'google.com' }, // North Korea (Korean)
    'mk': { hl: 'mk', googleDomain: 'google.mk' }, // North Macedonia (Macedonian)
    'no': { hl: 'no', googleDomain: 'google.no' }, // Norway (Norwegian)
    'om': { hl: 'ar', googleDomain: 'google.com.om' }, // Oman (Arabic)
    'pk': { hl: 'ur', googleDomain: 'google.com.pk' }, // Pakistan (Urdu)
    'pw': { hl: 'en', googleDomain: 'google.pw' }, // Palau (English)
    'ps': { hl: 'ar', googleDomain: 'google.ps' }, // Palestine (Arabic)
    'pa': { hl: 'es', googleDomain: 'google.com.pa' }, // Panama (Spanish)
    'pg': { hl: 'en', googleDomain: 'google.com.pg' }, // Papua New Guinea (English)
    'py': { hl: 'es', googleDomain: 'google.com.py' }, // Paraguay (Spanish)
    'pe': { hl: 'es', googleDomain: 'google.com.pe' }, // Peru (Spanish)
    'ph': { hl: 'tl', googleDomain: 'google.com.ph' }, // Philippines (Tagalog)
    'pl': { hl: 'pl', googleDomain: 'google.pl' }, // Poland (Polish)
    'pt': { hl: 'pt', googleDomain: 'google.pt' }, // Portugal (Portuguese)
    'qa': { hl: 'ar', googleDomain: 'google.com.qa' }, // Qatar (Arabic)
    'ro': { hl: 'ro', googleDomain: 'google.ro' }, // Romania (Romanian)
    'ru': { hl: 'ru', googleDomain: 'google.ru' }, // Russia (Russian)
    'rw': { hl: 'rw', googleDomain: 'google.rw' }, // Rwanda (Kinyarwanda)
    'kn': { hl: 'en', googleDomain: 'google.kn' }, // Saint Kitts and Nevis (English)
    'lc': { hl: 'en', googleDomain: 'google.lc' }, // Saint Lucia (English)
    'vc': { hl: 'en', googleDomain: 'google.com.vc' }, // Saint Vincent and the Grenadines (English)
    'ws': { hl: 'sm', googleDomain: 'google.ws' }, // Samoa (Samoan)
    'sm': { hl: 'it', googleDomain: 'google.sm' }, // San Marino (Italian)
    'st': { hl: 'pt', googleDomain: 'google.st' }, // São Tomé and Príncipe (Portuguese)
    'sa': { hl: 'ar', googleDomain: 'google.com.sa' }, // Saudi Arabia (Arabic)
    'sn': { hl: 'fr', googleDomain: 'google.sn' }, // Senegal (French)
    'rs': { hl: 'sr', googleDomain: 'google.rs' }, // Serbia (Serbian)
    'sc': { hl: 'en', googleDomain: 'google.sc' }, // Seychelles (English)
    'sl': { hl: 'en', googleDomain: 'google.com.sl' }, // Sierra Leone (English)
    'sg': { hl: 'en', googleDomain: 'google.com.sg' }, // Singapore (English)
    'sk': { hl: 'sk', googleDomain: 'google.sk' }, // Slovakia (Slovak)
    'si': { hl: 'sl', googleDomain: 'google.si' }, // Slovenia (Slovene)
    'sb': { hl: 'en', googleDomain: 'google.com.sb' }, // Solomon Islands (English)
    'so': { hl: 'so', googleDomain: 'google.so' }, // Somalia (Somali)
    'za': { hl: 'en', googleDomain: 'google.co.za' }, // South Africa (English primary)
    'kr': { hl: 'ko', googleDomain: 'google.co.kr' }, // South Korea (Korean)
    'ss': { hl: 'en', googleDomain: 'google.com' }, // South Sudan (English)
    'es': { hl: 'es', googleDomain: 'google.es' }, // Spain (Spanish)
    'lk': { hl: 'si', googleDomain: 'google.lk' }, // Sri Lanka (Sinhala)
    'sd': { hl: 'ar', googleDomain: 'google.sd' }, // Sudan (Arabic)
    'sr': { hl: 'nl', googleDomain: 'google.sr' }, // Suriname (Dutch)
    'se': { hl: 'sv', googleDomain: 'google.se' }, // Sweden (Swedish)
    'ch': { hl: 'de', googleDomain: 'google.ch' }, // Switzerland (German primary)
    'sy': { hl: 'ar', googleDomain: 'google.com.sy' }, // Syria (Arabic)
    'tw': { hl: 'zh', googleDomain: 'google.com.tw' }, // Taiwan (Chinese)
    'tj': { hl: 'tg', googleDomain: 'google.tj' }, // Tajikistan (Tajik)
    'tz': { hl: 'sw', googleDomain: 'google.co.tz' }, // Tanzania (Swahili)
    'th': { hl: 'th', googleDomain: 'google.co.th' }, // Thailand (Thai)
    'tg': { hl: 'fr', googleDomain: 'google.tg' }, // Togo (French)
    'to': { hl: 'to', googleDomain: 'google.to' }, // Tonga (Tongan)
    'tt': { hl: 'en', googleDomain: 'google.tt' }, // Trinidad and Tobago (English)
    'tn': { hl: 'ar', googleDomain: 'google.tn' }, // Tunisia (Arabic)
    'tr': { hl: 'tr', googleDomain: 'google.com.tr' }, // Turkey (Turkish)
    'tm': { hl: 'tk', googleDomain: 'google.tm' }, // Turkmenistan (Turkmen)
    'tv': { hl: 'en', googleDomain: 'google.tv' }, // Tuvalu (English)
    'ug': { hl: 'en', googleDomain: 'google.co.ug' }, // Uganda (English)
    'ua': { hl: 'uk', googleDomain: 'google.com.ua' }, // Ukraine (Ukrainian)
    'ae': { hl: 'ar', googleDomain: 'google.ae' }, // United Arab Emirates (Arabic)
    'gb': { hl: 'en', googleDomain: 'google.co.uk' }, // United Kingdom (English)
    'us': { hl: 'en', googleDomain: 'google.com' }, // United States (English)
    'uy': { hl: 'es', googleDomain: 'google.com.uy' }, // Uruguay (Spanish)
    'uz': { hl: 'uz', googleDomain: 'google.co.uz' }, // Uzbekistan (Uzbek)
    'vu': { hl: 'bi', googleDomain: 'google.vu' }, // Vanuatu (Bislama)
    'va': { hl: 'it', googleDomain: 'google.com' }, // Vatican City (Italian)
    've': { hl: 'es', googleDomain: 'google.co.ve' }, // Venezuela (Spanish)
    'vn': { hl: 'vi', googleDomain: 'google.com.vn' }, // Vietnam (Vietnamese)
    'ye': { hl: 'ar', googleDomain: 'google.com.ye' }, // Yemen (Arabic)
    'zm': { hl: 'en', googleDomain: 'google.co.zm' }, // Zambia (English)
    'zw': { hl: 'en', googleDomain: 'google.co.zw' }, // Zimbabwe (English)
    'default': { hl: 'en', googleDomain: 'google.com' } // Fallback
};