class Country {
  final String name;
  final String code;

  const Country(this.name, this.code);
}

final List<Country> countries = [
  Country('Afghanistan', 'af'),
  Country('Albania', 'al'),
  Country('Algeria', 'dz'),
  Country('Andorra', 'ad'),
  Country('Angola', 'ao'),
  Country('Argentina', 'ar'),
  Country('Armenia', 'am'),
  Country('Australia', 'au'),
  Country('Austria', 'at'),
  Country('Azerbaijan', 'az'),
  Country('Bahamas', 'bs'),
  Country('Bahrain', 'bh'),
  Country('Bangladesh', 'bd'),
  Country('Belarus', 'by'),
  Country('Belgium', 'be'),
  Country('Belize', 'bz'),
  Country('Brazil', 'br'),
  Country('Bulgaria', 'bg'),
  Country('Canada', 'ca'),
  Country('China', 'cn'),
  Country('Colombia', 'co'),
  Country('Croatia', 'hr'),
  Country('Cuba', 'cu'),
  Country('Cyprus', 'cy'),
  Country('Czech Republic', 'cz'),
  Country('Denmark', 'dk'),
  Country('Egypt', 'eg'),
  Country('Estonia', 'ee'),
  Country('Finland', 'fi'),
  Country('France', 'fr'),
  Country('Georgia', 'ge'),
  Country('Germany', 'de'),
  Country('Greece', 'gr'),
  Country('Hungary', 'hu'),
  Country('Iceland', 'is'),
  Country('India', 'in'),
  Country('Indonesia', 'id'),
  Country('Iran', 'ir'),
  Country('Iraq', 'iq'),
  Country('Ireland', 'ie'),
  Country('Israel', 'il'),
  Country('Italy', 'it'),
  Country('Japan', 'jp'),
  Country('Kazakhstan', 'kz'),
  Country('Kenya', 'ke'),
  Country('Kuwait', 'kw'),
  Country('Latvia', 'lv'),
  Country('Lebanon', 'lb'),
  Country('Libya', 'ly'),
  Country('Liechtenstein', 'li'),
  Country('Lithuania', 'lt'),
  Country('Luxembourg', 'lu'),
  Country('Malaysia', 'my'),
  Country('Malta', 'mt'),
  Country('Mexico', 'mx'),
  Country('Moldova', 'md'),
  Country('Monaco', 'mc'),
  Country('Mongolia', 'mn'),
  Country('Montenegro', 'me'),
  Country('Morocco', 'ma'),
  Country('Nepal', 'np'),
  Country('Netherlands', 'nl'),
  Country('New Zealand', 'nz'),
  Country('Nigeria', 'ng'),
  Country('North Korea', 'kp'),
  Country('Norway', 'no'),
  Country('Pakistan', 'pk'),
  Country('Panama', 'pa'),
  Country('Peru', 'pe'),
  Country('Philippines', 'ph'),
  Country('Poland', 'pl'),
  Country('Portugal', 'pt'),
  Country('Qatar', 'qa'),
  Country('Romania', 'ro'),
  Country('Russia', 'ru'),
  Country('Saudi Arabia', 'sa'),
  Country('Serbia', 'rs'),
  Country('Singapore', 'sg'),
  Country('Slovakia', 'sk'),
  Country('Slovenia', 'si'),
  Country('South Africa', 'za'),
  Country('South Korea', 'kr'),
  Country('Spain', 'es'),
  Country('Sri Lanka', 'lk'),
  Country('Sweden', 'se'),
  Country('Switzerland', 'ch'),
  Country('Syria', 'sy'),
  Country('Taiwan', 'tw'),
  Country('Thailand', 'th'),
  Country('Turkey', 'tr'),
  Country('Ukraine', 'ua'),
  Country('United Arab Emirates', 'ae'),
  Country('United Kingdom', 'gb'),
  Country('United States', 'us'),
  Country('Uruguay', 'uy'),
  Country('Uzbekistan', 'uz'),
  Country('Vatican City', 'va'),
  Country('Venezuela', 've'),
  Country('Vietnam', 'vn'),
  Country('Yemen', 'ye'),
];
